services:
  database:
    deploy:
      resources:
        limits:
          memory: 3000M
    image: postgres:16
    restart: always
    shm_size: 50mb
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER $POSTGRES_DATABASE" ]
      interval: 5s
      retries: 5
      timeout: 3s
    networks:
      - app-network
    hostname: database

  bookstore-service:
    container_name: bookstore-service
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    env_file:
      - ../.env
    environment:
      - JAVA_OPTS=${JAVA_OPTS:-}
    depends_on:
      database:
        condition: service_started
    links:
      - database
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge